### DISCUSSION TITLE
RFC: GitHub Action for GraalVM (GR-33015)

### DISCUSSION THREAD

**Discussion by fniephaus** [oracle/graal#4150] [Ideas] [answered]
We are working on a `setup-graalvm` GitHub Action (GHA) to simplify setting up different versions and configurations of GraalVM. We would like to use this discussion to collect potential use cases and discuss possible features. Please feel free to comment below.

## Potential Use Cases

- Build native images using GHA (also in combination with gradle/maven)
- Simplify testing setups (including oracle/graal and GraalVM languages)
- Run GraalVM languages as part of a GitHub workflow
- Deploy GraalVM distributions

## Initial Features

- Sets `$JAVA_HOME` and `$GRAALVM_HOME` to the selected GraalVM build for the current platform
- Adds `$GRAALVM_HOME/bin` to `$PATH` so that `gu` and all installed components are directly accessible
- Allows GraalVM to be built from tip (slowdown expected)
- Supports Ubuntu/Windows/macOS on amd64 (aarch64 currently not officially supported by GHA)
- Installs dependencies for selected GraalVM components (e.g., msvc for Native Image on Windows or libssl for TruffleRuby) and runs post-install hooks

### GitHub workflow example

```yml
steps:
- uses: actions/checkout@latest
- uses: graalvm/setup-graalvm@1.0
  with:
    version: '22.0.0'
    java-version: '11'
    components: native-image,R,llvm-toolchain
```

### Options

- **`version`**: any GraalVM release (`XX.YY.ZZ`), `latest` for the latest release, or `trunk` for building from tip (maybe `dev` as a compromise to save some time?) Defaults to the latest release.
- **`java-version`**: `11` or `17` (`8` and `16` supported for old releases). Defaults to latest support Java version.
- **`components`**: comma-separated list of GU components supported for the selected GraalVM version.
- **`github-token`**: token for communication with the GitHub API. If set to `${{ secrets.GITHUB_TOKEN }}`, helps to reduce rate limiting issues.
- **`set-java-home`**: instructs the action to set `$JAVA_HOME`. Defaults to `true`.

## Possible Future Features

- GHA does not officially support aarch64, but self-hosted workers can be based on aarch64 and there are emulation workflows (e.g., [uraimo/run-on-arch-action](https://github.com/uraimo/run-on-arch-action), [GraalVM-related example](https://github.com/hpi-swa/trufflesqueak/blob/ffb4b508635ee96e57ded2cd92c7551a629c51cb/.github/workflows/ci.yml#L155-L174))
- We recommend using different build jobs but if there are use cases, provide a utility to switch between multiple versions within one build job (e.g., `switch-graalvm "21.3.0-java11"`).
- Add support for Mandrel (releases should be relatively simple to support, building Mandrel from tip requires [additional steps](https://github.com/graalvm/mandrel-packaging)).

*Note that GitHub Action workers already [come with the latest JDK11-based GraalVM release](https://github.com/actions/virtual-environments/issues/2197).*

**Comment by chrisseaton** [comment]
Some languages such as Ruby need a few system libraries or other components installed to be useful, so the Action should install those.

**Reply by fniephaus** [reply]
Good point, I added that to the list of features.

**Reply by eregon** [reply]
Actually, at least GH hosted runners, there is no need to install anything for truffleruby, and the truffleruby from https://github.com/ruby/setup-ruby is already recompiled against each OS-version's existing libssl.

**Comment by zakkak** [comment]
That sounds great @fniephaus 

We would like to see an option for using Mandrel as well (I am willing to contribute the corresponding parts).

Something like:
```
steps:
- uses: actions/checkout@latest
- uses: graalvm/setup-graalvm@1.0
  with:
    version: '22.0.0'
    java-version: '11'
    distribution: 'mandrel'
```

* `distribution` would be optional and set to `'graalvm'` by default
* `components` would be ignored in the case of the Mandrel distribution as it only provides `native-image`

**Reply by fniephaus** [reply]
Thanks, I'll add this to the list. It might not make it into the very first release but we'll keep this in mind.

**Reply by fniephaus** [reply]
setup-java supports a "distribution" key but it seems we would only add it for Mandrel support. Do you think it is reasonable to support Mandrel through the "version" key for now? We could reserve a namespace "mandrel-" and it could then be used like this: "version: mandrel-latest" or "version: mandrel-21.3.0.0-Final".

What do you think?

**Reply by zakkak** [reply]
That sounds good.

FTR this is now implemented in https://github.com/graalvm/setup-graalvm/pull/1

I assume `mandrel-trunk` should then be used for [Mandrel builds from source](https://github.com/graalvm/setup-graalvm/pull/2).

**Comment by borkdude** [comment]
Good to see that this is being worked on. FWIW, I've been using https://github.com/marketplace/actions/setup-graalvm-environment in some projects too. /cc @delaguardo.

**Comment by ricardozanini** [comment]
I've been using @DeLaGuardo's action too, and it fills my needs. Maybe having an option to install the `native-image` automatically without requiring an extra step would be excellent.

**Reply by fniephaus** [reply]
Do you think a dedicate Native Image example in the action's README would be sufficient? All you'd have to do is to explicitly mention `native-image` in the list of components:
```yml
- uses: graalvm/setup-graalvm@1.0
  with:
    version: '22.0.0'
    java-version: '11'
    components: native-image
```

While it is a common use case, I'm not sure we want to special case it given that the above example is simple. Any other opinions?

**Reply by helpermethod** [reply]
The flag for installing the `native-image` command is mandatory for multiplatform builds, as otherwise you have to juggle with different shells (`powershell`, `bash`).

**Reply by fniephaus** [reply]
I'm not sure I understand your comment. Could you elaborate a bit please? Multi-platform builds across different build jobs I assume?

On Windows, we recommend using x64 Native Tools Command Prompt for Native Image and I'd say that's what workflows are supposed to use, too. Not yet sure how to spawn that best (e.g. via PowerShell, cmd, or bash). Any experience reports are welcome!

**Reply by ricardozanini** [reply]
> Do you think a dedicate Native Image example in the action's README would be sufficient? All you'd have to do is to explicitly mention native-image in the list of components:

Definitely! Today what we have to do is to run a command to first install GraalVM and then another to install `native-image`. For example:

```yaml
    steps:
      - uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.3.0'
          java: 'java11'

      - name: Install native-image component
        run: gu install native-image
```
