### ISSUE TITLE
[Truffle] Possible Footprint Improvement for DynamicObjectLibrary

### ISSUE THREAD

**Issue by smarr** [oracle/graal#4041]
On TruffleRuby, I am seeing for unit-test code a lot of AST sub trees of the shape:

```yaml
Cached:
  - AnyKey:
      - MissingKeyIdentity
```

It seems that reading a missing field requires 3 nodes, and is one of the most common subtrees I see on the ActiveSupport unit tests.

Perhaps there's potential to reduce the footprint for those.

/cc @eregon
