### ISSUE TITLE
@Validated in @ConfigurationProperties doesn't work when running in native image

### ISSUE THREAD

**Issue by KimSeongIl** [oracle/graal#6976]
**Describe the issue**

It worked fine on the jvm, but when I run it on the native image I get an error.
But if I remove the Pattern annotation, it works fine.

Why is this issue occurring?
How can I solve this problem?

**Steps to reproduce the issue**

1. git clone https://github.com/KimSeongIl/demo.git
2. nativeCompile
3. nativeRun

DemoContext.kt
```kotlin
@ConfigurationProperties(prefix = "demo.context")
@Validated
class DemoContext {

    var exclude: List<Exclude> = mutableListOf()

    data class Exclude(
        var url: List<String>? = null,

        var httpMethod: List<HttpMethod>? = null,

        var httpStatus: List<@Pattern(regexp="^([1-5][x|X]{2}|[1-5][0-9]{2})\$") String>? = null,

        var elapsedTime: Long? = null
    )

}
```

application.yml
```yaml
demo:
  context:
    exclude:
      - httpStatus: 2xx
```

nativeRun result
```
Binding to target [Bindable@517a5ddb type = java.util.List<DemoContext$Exclude>, value = 'provided', annotations = array<Annotation>[[empty]]] failed:

    Property: demo.context.exclude[0].httpstatus
    Value: "2xx"
    Origin: class path resource [application.yml] - 31:21
    Reason: The elements [demo.context.exclude[0].httpstatus] were left unbound.

Action:

Update your application's configuration
```

**Describe GraalVM and your environment**

spring boot version: 3.1.0
graalvm plugin version: id("org.graalvm.buildtools.native") version "0.9.20"
graalvm version: 22.3.r17

**More details**

https://github.com/spring-projects/spring-framework/issues/30760

discussed in the above issue
@sdeleuze   said it looks like a graalvm bug.
